### PR TITLE
Add adaptive links

### PR DESCRIPTION
**Pull request by CasperMcFadden95**

### CODE REVIEW

**Comment by ipstreet312** [comment]
Hi @CasperMcFadden95 and thank you very much for your contributions. Just an issue to raise : nessmatv seems have a synchro bug by its video and audio streams mixing. Could you look at please, on its master reference file may be ? Thanks a lot again, regards

**Comment by CasperMcFadden95** [comment]
> Hi @CasperMcFadden95 and thank you very much for your contributions. Just an issue to raise : nessmatv seems have a synchro bug by its video and audio streams mixing. Could you look at please, on its master reference file may be ? Thanks a lot again, regards

Hi, I copied it from https://www.bledflix.tv which means the source is bad. You can revert my change if it's causing issues. Thanks

**Comment by ipstreet312** [comment]
> > Hi @CasperMcFadden95 and thank you very much for your contributions. Just an issue to raise : nessmatv seems have a synchro bug by its video and audio streams mixing. Could you look at please, on its master reference file may be ? Thanks a lot again, regards
> 
> Hi, I copied it from https://www.bledflix.tv which means the source is bad. You can revert my change if it's causing issues. Thanks

Thanks but source is well, video is fine and audio too, just mixing is on a bad state what is strange that's why my remarks, thanks and regards

**Comment by CasperMcFadden95** [comment]
I'm not sure why. You can revert if you want.

**Comment by ipstreet312** [comment]
> I'm not sure why. You can revert if you want.

Strange situation, but I believe, may be in the future it could be solved. And so I prefer to keep this already produced work as a value anyway. Thank you again for your message and best regards. FYI : unfortunately bledflix is partialy and not accessible from France and so it is difficult to investigate.

**Pull request merged**
