### PR TITLE
Add Equidia channels

### PR DESCRIPTION
**Pull request by schumijo**
Linked to #12 

Seems to be working fine for few days on my side. 
Feel free to improve

Not sure on which frequency links should be updated. 
We can try every 6 hours
@ipstreet312 can you create an action for this ?

### CODE REVIEW

**Comment by ipstreet312** [comment]
Thank you @schumijo but what we should do to finalize getting equidia's m3u8 link?
I created https://github.com/ipstreet312/freeiptv/blob/master/feed/equidia.m3u8 but i dont know what to do after.
Thank you for your help and interest, Kind Regards

**Comment by ipstreet312** [comment]
sorry to have disturbed you @schumijo  : ok I found the solution and created a yml file like for others ch entries.
But m3u8 content file is empty, just first line is build. If you could look why, I hope you have explanation.
Sorry and thanks again a lot, see you best cheers

**Comment by schumijo** [comment]
OK will take a look, need to learn how to create action on my github 😅

**Comment by schumijo** [comment]
Ok I found the error 
{"status":"ko","msg":"geoblocking error country: US ip: 40.77.125.163 "}

**Pull request merged**
